
prompts_file: "configs/sd15_child_to_adult/prompt.yaml"

pretrained_model:
  name_or_path: "runwayml/stable-diffusion-v1-5"
  v2: false
  v_pred: false
  clip_skip: 1

network:
  rank: 2
  alpha: 1.0

train:
  precision: bfloat16
  noise_scheduler: "ddim"
  iterations: 5000
  batch_size: 1
  lr: 0.0001
  unet_lr: 0.0001
  text_encoder_lr: 5e-05
  optimizer_type: "AdamW8bit"
  lr_scheduler: "cosine_with_restarts"
  lr_warmup_steps: 500
  lr_scheduler_num_cycles: 3
  max_denoising_steps: 20

save:
  name: "sd15_child_to_adult"
  path: "output/sd15_child_to_adult"
  per_steps: 500
  precision: bfloat16

logging:
  use_wandb: false
  interval: 500
  seed: 0
  generate_num: 2
  run_name: "sd15_child_to_adult"
  verbose: false
  prompts: ['child']

other:
  use_xformers: true